# Generated by Django 2.1.1 on 2018-09-23 18:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', models.CharField(max_length=100, null=True)),
                ('subdivisions', models.CharField(max_length=50, null=True)),
                ('mail', models.CharField(max_length=150, null=True)),
                ('city_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=7)),
                ('image', models.ImageField(null=True, upload_to='profile_image')),
                ('locaton', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
