# Generated by Django 2.0.7 on 2018-09-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbprofile',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='tbprofile',
            name='image_url',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tbprofile',
            name='mail',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tbprofile',
            name='post',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbprofile',
            name='subdivisions',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
