# Generated by Django 2.0.7 on 2018-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0002_auto_20180921_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tbprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
