# Generated by Django 2.0.7 on 2018-09-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataType', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['data_type']},
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='DataType.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('data_type', 'data')},
        ),
    ]
